apiVersion: apps/v1
kind: Deployment
metadata:
  name: javawebappdc
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: javawebapp
  template:
    name: javawebappdcpod
    labels:
      app: javawebapp
  spec:
  - containers:
      name: javawebappcontainer
      image: ashokit/javawebapp
      ports:
      - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: javawebappsvc
spec:
  type: NodePort
  selector:
    app: javawebapp
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30002
